packages:
  - "packages/*"
  - "apps/*"
  - "tests/*"
  - "website"

catalog:
  "@rspack/core": ^1.2.7
  "@rslib/core": ^0.5.3
  "@swc/helpers": ~0.5.15
  "terser-webpack-plugin": ^5.3.11
  "typescript": ^5.7.2
  "webpack": ^5.98.0

catalogs:
  testers:
    "react-native-test-app": 4.2.1
