packages:
  - "packages/*"
  - "apps/*"
  - "tests/*"
  - "website"

catalog:
  "@rspack/core": ^1.4.2
  "@rslib/core": ^0.6.3
  "@swc/helpers": ~0.5.17
  "@types/node": ^20
  "terser-webpack-plugin": ^5.3.14
  "typescript": ^5.8.3
  "webpack": ^5.99.5
  "react": "19.0.0"
  "react-native": "0.79.1"
  "vitest": ^2.0.5

catalogs:
  testers:
    "react-native-test-app": 4.3.3
