packages:
  - "packages/*"
  - "apps/*"
  - "tests/*"
  - "website"

catalog:
  "@rspack/core": ^1.2.2
  "@swc/helpers": ~0.5.15
  "typescript": ^5.7.2

catalogs:
  testers:
    "react-native-test-app": 4.0.7
