packages:
  - "packages/*"
  - "apps/*"
  - "tests/*"
  - "website"

catalog:
  "@rspack/core": ^1.4.11
  "@rslib/core": ^0.6.3
  "@swc/helpers": ~0.5.17
  "@types/node": ^20
  "expo": ^53
  "terser-webpack-plugin": ^5.3.14
  "typescript": ^5.8.3
  "webpack": ^5.99.9
  "react": "19.1.0"
  "react-native": "0.81.0"
  "vitest": ^2.0.5

catalogs:
  testers:
    "@types/react": ^19.1.0
    "react-native-test-app": 4.4.7
    "@react-native/babel-preset": "0.81.0"
    "@react-native/typescript-config": "0.81.0"
    "@react-native-community/cli": "20.0.0"
    "@react-native-community/cli-platform-android": "20.0.0"
    "@react-native-community/cli-platform-ios": "20.0.0"
