/**
 * This is the list of modules that React Native publicly exports and that we want to require lazily.
 * Source: https://github.com/facebook/react-native/blob/main/packages/react-native-babel-preset/src/configs/lazy-imports.js
 */

export const REACT_NATIVE_LAZY_IMPORTS: string[] = [
  'AccessibilityInfo',
  'ActivityIndicator',
  'Button',
  'DatePickerIOS',
  'DrawerLayoutAndroid',
  'FlatList',
  'Image',
  'ImageBackground',
  'InputAccessoryView',
  'KeyboardAvoidingView',
  'Modal',
  'Pressable',
  'ProgressBarAndroid',
  'ProgressViewIOS',
  'SafeAreaView',
  'ScrollView',
  'SectionList',
  'Slider',
  'Switch',
  'RefreshControl',
  'StatusBar',
  'Text',
  'TextInput',
  'Touchable',
  'TouchableHighlight',
  'TouchableNativeFeedback',
  'TouchableOpacity',
  'TouchableWithoutFeedback',
  'View',
  'VirtualizedList',
  'VirtualizedSectionList',

  // APIs
  'ActionSheetIOS',
  'Alert',
  'Animated',
  'Appearance',
  'AppRegistry',
  'AppState',
  'AsyncStorage',
  'BackHandler',
  'Clipboard',
  'DeviceInfo',
  'Dimensions',
  'Easing',
  'ReactNative',
  'I18nManager',
  'InteractionManager',
  'Keyboard',
  'LayoutAnimation',
  'Linking',
  'LogBox',
  'NativeEventEmitter',
  'PanResponder',
  'PermissionsAndroid',
  'PixelRatio',
  'PushNotificationIOS',
  'Settings',
  'Share',
  'StyleSheet',
  'Systrace',
  'ToastAndroid',
  'TVEventHandler',
  'UIManager',
  'ReactNative',
  'UTFSequence',
  'Vibration',

  // Plugins
  'RCTDeviceEventEmitter',
  'RCTNativeAppEventEmitter',
  'NativeModules',
  'Platform',
  'processColor',
  'requireNativeComponent',
];
