name: "\U0001F41B Bug report"
description: Report an issue with Re.Pack
labels: ["status:new", "type:bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx react-native info`
      render: shell
      placeholder: System, Binaries, Managers, SDKs, IDEs, Languages, etc.
    validations:
      required: true
  - type: input
    id: repack-version
    attributes:
      label: Re.Pack Version
      description: The version of Re.Pack you are using.
      placeholder: 4.0.0
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo that can reproduce the problem you ran into. Issues without reproduction steps are likely to stall.
      placeholder: Reproduction URL
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described. For example, the problem happens only in release mode, or only on Android, etc.
      placeholder: Run `yarn install` followed by `yarn react-native webpack-bundle`
    validations:
      required: true
