export const VERBOSE_ENV_KEY = 'REPACK_VERBOSE';
export const WORKER_ENV_KEY = 'REPACK_WORKER';

export const BUNDLE_FILENAME_ENV_KEY = 'REPACK_BUNDLE_FILENAME';
export const SOURCEMAP_FILENAME_ENV_KEY = 'REPACK_SOURCEMAP_FILENAME';
export const ASSETS_DEST_ENV_KEY = 'REPACK_ASSETS_DEST';

export const RSPACK_TOKIO_THREADS_ENV_KEY = 'TOKIO_WORKER_THREADS';
export const RSPACK_RAYON_THREADS_ENV_KEY = 'RAYON_NUM_THREADS';

export const EXPERIMENTAL_CACHE_ENV_KEY = 'REPACK_EXPERIMENTAL_CACHE';
