export const VERBOSE_ENV_KEY = 'REPACK_VERBOSE';
export const WORKER_ENV_KEY = 'REPACK_WORKER';

export const BUNDLE_FILENAME_ENV_KEY = 'REPACK_BUNDLE_FILENAME';
export const SOURCEMAP_FILENAME_ENV_KEY = 'REPACK_SOURCEMAP_FILENAME';
export const ASSETS_DEST_ENV_KEY = 'REPACK_ASSETS_DEST';
