import path from 'path';
import fs from 'fs-extra';
import execa from 'execa';

/**
 * {@link composeSourceMaps} options.
 */
interface ComposeSourceMapsOptions {
  reactNativePath: string;
  packagerMapPath: string;
  compilerMapPath: string;
}

/**
 * Composes source maps generated by webpack-bundle and Hermes.
 *
 * Removes original source map files.
 */
export const composeSourceMaps = async ({
  reactNativePath,
  packagerMapPath,
  compilerMapPath,
}: ComposeSourceMapsOptions) => {
  const composedSourceMapPath = packagerMapPath + '.composed';

  await execa('node', [
    path.join(reactNativePath, 'scripts/compose-source-maps.js'),
    packagerMapPath,
    compilerMapPath,
    '-o',
    composedSourceMapPath,
  ]);

  // Remove intermediate files
  await fs.unlink(packagerMapPath);
  await fs.unlink(compilerMapPath);

  await fs.rename(composedSourceMapPath, packagerMapPath);
};
