source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
#
# 3.1 is the floor for activesupport >= 7.2, but 3.4 is the real floor here:
# on Ruby <= 3.3 CocoaPods intermittently dies with "pathname contains null
# byte" while resolving pnpm's symlinked node_modules (CocoaPods#12866).
ruby '>= 3.4'

# Exclude problematic versions of cocoapods that cause build failures.
# activesupport is floored at the release carrying the security fixes.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 7.2.3.1'
gem 'xcodeproj', '< 1.26.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
