module.exports = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      items: ['getting-started'],
    },
  ],
  configuration: [
    {
      type: 'category',
      label: 'Configuration',
      items: ['configuration/webpack-config'],
    },
    {
      type: 'category',
      label: 'Functions',
      items: [
        'api/functions/getContext',
        'api/functions/getDevServerOptions',
        'api/functions/getEntry',
        'api/functions/getMode',
        'api/functions/getPlatform',
        'api/functions/getReactNativePath',
        'api/functions/isMinimizeEnabled',
        'api/functions/getInitializationEntries',
        'api/functions/getPublicPath',
        'api/functions/getResolveOptions',
      ].map((docId) => ({ type: 'ref', id: docId })),
    },
    {
      type: 'category',
      label: 'Webpack Plugins',
      items: [
        'api/classes/AssetsPlugin',
        'api/classes/DevServerPlugin',
        'api/classes/JavaScriptLooseModePlugin',
        'api/classes/LoggerPlugin',
        'api/classes/OutputPlugin',
        'api/classes/TargetPlugin',
      ].map((docId) => ({ type: 'ref', id: docId })),
    },
  ],
  api: [
    {
      type: 'category',
      label: 'API',
      items: [
        'api/index',
        {
          type: 'category',
          label: 'Classes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/classes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/functions',
            },
          ],
        },
        {
          type: 'category',
          label: 'Interfaces',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/interfaces',
            },
          ],
        },
        {
          type: 'category',
          label: 'Variables',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/variables',
            },
          ],
        },
      ],
    },
  ],
};
